[package]
name = "cli"
version = "0.0.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo"] }
common = { path = "../common" }
ctrlc = "3.4.5"
tokio = { version = "1.41.0", features = ["full"] }
