[package]
name = "common"
version = "0.0.1"
edition = "2021"

[dependencies]
bytes = "1.8.0"
dirs = "5.0.1"
reqwest = { version = "0.12.8", features = ["json"] }
serde = { version = "1.0.213", features = ["serde_derive"] }
zip = "2.2.0"
zip-extract = "0.2.1"
